services:
    mongodb:
        image: mongo
        container_name: mongodb
        ports:
            - 27017:27017
        restart: always
        volumes:
            - .mongodb:/data/db
        environment:
            - MONGO_INITDB_ROOT_USERNAME=root
            - MONGO_INITDB_ROOT_PASSWORD=password
            - MONGO_INITDB_DATABASE=database
        networks:
            - google-drive-network

    api:
        build:
            context: ./backend
        container_name: api
        ports:
            - 8000:8000
        volumes:
            - ./backend:/app
            - /app/node_modules
        environment:
            - CHOKIDAR_USEPOLLING=true
        depends_on:
            - mongodb
        networks:
            - google-drive-network

    web:
        build:
            context: ./frontend
        container_name: web
        ports:
            - 5173:5173
        volumes:
            - ./frontend:/app
            - /app/node_modules
        environment:
            - VITE_API_URL=http://localhost:8000
            - CHOKIDAR_USEPOLLING=true
        depends_on:
            - api
        networks:
            - google-drive-network

volumes:
    mongo-data:

networks:
    google-drive-network:
        driver: bridge
