version: "3.9"
services:
    api:
        build:
            context: ./backend
        container_name: api
        ports:
            - 8000:8000
        volumes:
            - ./backend:/app
            - /app/node_modules
        environment:
            - CHOKIDAR_USEPOLLING=true

    # web:
    #     build:
    #         context: ./frontend
    #     container_name: web
    #     ports:
    #         - 5173:5173
    #     volumes:
    #         - ./frontend:/app
    #         - /app/node_modules
    #     environment:
    #         - VITE_API_URL=http://localhost:8000
    #         - CHOKIDAR_USEPOLLING=true
    #     depends_on:
    #         - api
