FROM node:20-slim
WORKDIR /app

RUN apt-get update && apt-get install -y \
    unoconv \
    ffmpeg \
    imagemagick \
    curl \
    && rm -rf /var/lib/apt/lists/*

COPY package.json ./
RUN npm install

COPY . .
EXPOSE 8000

CMD ["npm","run","dev"]